---
layout: post
title: "Declarative Pipeline for Maven Projects"
tags:
- tutorial
- pipeline
- declarative
- maven
- java
author: lnewman
---

NOTE: This is a guest post by link:https://github.com/bitwiseman[Liam Newman],
Technical Evangelist at link:https://cloudbees.com[CloudBees].


== Declare Your Pipelines!

Jenkin Declarative Pipeline 1.0 is here!
It is now included automatically with J

This is first in a series of blog posts that will showing how key features of
Declarative Pipeline and how to use them.
For several of these, I'll be revisiting my previous series of posts on using with various plugins
with (Scripted) Pipline,
and comparing how those are implemented in Declarative Pipeline.

To start though, let's get familiar with the basic structure of a Declarative Pipeline
using a simple pipeline for a basic Maven-based Jave project -
the Jenkins JUnit plugin.
We'll create a minimal Declarative Pipeline,
add the configuration needed to use Maven and the JDK,
and finally run Maven to build the plugin.

== Setup

With Declarative, it is still possible to run Pipelines edited directly in the Jenkis web UI,
but one of the key features of "Pipeline as Code" is checking-in and being able to track changes.
For this post, I'm going to use the `blog/add-declarative-pipeline` branch of my fork of the JUnit plugin.
I'm going to setup a Multi-branch Pipeline and point it at my repository.

// TODO Image of the Multi-branch configuration

I've also set this pipeline's git client to automatically "clean after checkout"
and to only keep the ten most recent runs.

== Writing a Minimal Pipeline

As has been said before,
Declarative Pipeline provides a more structured, "opinionated" way to create pipelines.

I'm going to start by adding a minimal Declarative Pipeline to my branch.
Below is a minimal Pipeline (with annotations) that just prints a message:

[pipeline]
----
// Declarative //
pipeline { // <1>
    agent any // <2> <3>
    stages { // <4>
        stage('Build') { // <5>
            steps { // <6>
               echo 'This is a minimal pipeline.' // <7>
            }
        }
    }
}
// Scripted //
node { // <2>
    checkout scm // <3>
    stage ('Build') { // <4>
        echo 'This is a minimal pipeline.' // <6>
    }
}
----
<1> All Declarative Pipelines start with a `pipeline` section.
<2> Select where to run this Pipeline, in this case "any" agent regardless of label.
<3> Declarative automatically does`checkout scm` on the agent,
whereas this must by done explicitly in Scripted Pipeline.
<4> A minimal Declarative Pipeline is defined a series of stages.
<5> Run the "Build" stage.
<6> Each stage in a Declarative Pipeline runs a series of steps.
<7> Run the `echo` step to print a message in the log.

NOTE: If you are familiar with Scripted Pipeline, you can expand the above
Declarative code sample to show the Scripted equivalent.

Once I add above Pipeline to my `Jenkinsfile` and run "Branch Indexing",
my Jenkins will pick it up and run run it.

// TODO: Image of completed run

.Log Output
[source]
----
[Pipeline] node
Running on osx_mbp in /Users/bitwiseman/jenkins/agents/osx_mbp/workspace/blog_add-declarative-pipeline
[Pipeline] {
[Pipeline] stage
[Pipeline] { (Declarative: Checkout SCM)
[Pipeline] checkout
Cloning the remote Git repository
{ ... truncated 20 lines ... }
[Pipeline] }
[Pipeline] // stage
[Pipeline] stage
[Pipeline] { (Build)
[Pipeline] echo
This is a minimal pipeline
[Pipeline] }
[Pipeline] // stage
[Pipeline] }
[Pipeline] // node
[Pipeline] End of Pipeline
Finished: SUCCESS
----

Declarative Pipeline code  may be little more verbose than the equivalent Scripted Pipeline,
but the added detail gives a clearer, more consistent view of what each Pipeline is supposed to to do.
It also gives us a structure into which we can add more configuration details about this pipeline.

== Adding Tools to Pipeline

The next thing we'll add in this Pipeline is a `tools` section to let us use Maven in this pipeline.
The `tools` section is one of several sections we can add under `pipeline`
that set configuration for the rest of the pipeline.
(We'll look at the others in including `agent` in a later post.)
Each tool entry will make whatever settings changes,
such as updating `PATH` or other environment variables,
to make the named tool available in the current pipeline.
It will also automatically install the named tool if that tool is configured to do so
under "Managing Jenkins" -> "Global Tool Configuration".


.Jenkinsfile
[pipeline]
----
// Declarative
pipeline {
    agent any
    tools { // <1>
        maven 'Maven 3.3.9' // <2>
        jdk 'jdk8' // <3>
    }
    stages {
        stage ('Initialize') {
            steps {
                sh '''
                    echo "PATH = ${PATH}"
                    echo "M2_HOME = ${M2_HOME}"
                ''' // <4>
            }
        }

        stage ('Build') {
            steps {
                echo 'This is a minimal pipeline.'
            }
        }
    }
}
// Scripted Not Defined
----
<1> `tools` section for adding tool settings.
<2> Configure this pipeline to use the Maven version matching "Maven 3.3.9"
(configured in "Managing Jenkins" -> "Global Tool Configuration").
<3> Configure this pipeline to use the Maven version matching "jdk8"
(configured in "Managing Jenkins" -> "Global Tool Configuration").
<4> These will show the changes to `PATH` and `M2_HOME`.


When we run this updated pipeline the same way we did the first we see that the
Declarative Pipeline has added another stage called "Declarative: Tool Install":

//TODO Add image of stage view

In the log output, we see that "Meven 3.3.9" gets installed,
and the `PATH` and `M2_HOME` environment variables are set:

.Log Output
[source]
----
{ ... truncated lines ... }
[Pipeline] { (Declarative: Tool Install)
[Pipeline] tool
Unpacking https://repo.maven.apache.org/maven2/org/apache/maven/apache-maven/3.3.9/apache-maven-3.3.9-bin.zip
to /Users/bitwiseman/jenkins/agents/osx_mbp/tools/hudson.tasks.Maven_MavenInstallation/Maven_3.3.9
on osx_mbp
{ ... }
PATH = /Library/Java/JavaVirtualMachines/jdk1.8.0_92.jdk/Contents/Home/bin:/Users/bitwiseman/jenkins/agents/osx_mbp/tools/hudson.tasks.Maven_MavenInstallation/Maven_3.3.9/bin:...
M2_HOME = /Users/bitwiseman/jenkins/agents/osx_mbp/tools/hudson.tasks.Maven_MavenInstallation/Maven_3.3.9
{ ... }
----


== Running a Maven Build

Finally, running a Maven build is trival.
The `tools` section already added Maven and JDK8 to the `PATH`,
all we need to do is call `mvn install`.
It would be nice if I could split the build and the testing into separate stages,
but Maven is famous for not liking when people do that.
I'll leave it alone for now.


.Jenkinsfile
[pipeline]
----
// Declarative
pipeline {
    agent any
    tools {
        maven 'Maven 3.3.9'
        jdk 'jdk8'
    }
    stages {
        stage ('Initialize') {
            steps {
                sh '''
                    echo "PATH = ${PATH}"
                    echo "M2_HOME = ${M2_HOME}"
                '''
            }
        }

        stage ('Build') {
            steps {
                sh 'mvn install' // <1>
            }
        }
    }
}
// Scripted Not Defined
----
<1> Call `mvn`, the version configured by the `tools` section will be first on the path.

Below are the Stage view and a sample of log output for this last revision:

// TODO Add stage view image


.Log Output
[source]
----
{ ... truncated lines ... }
+ mvn install
[INFO] Scanning for projects...
[WARNING] The POM for org.jenkins-ci.tools:maven-hpi-plugin:jar:1.119 is missing, no dependency information available
[WARNING] Failed to build parent project for org.jenkins-ci.plugins:junit:hpi:1.20-SNAPSHOT
[INFO]
[INFO] ------------------------------------------------------------------------
[INFO] Building JUnit Plugin 1.20-SNAPSHOT
[INFO] ------------------------------------------------------------------------
[INFO]
[INFO] --- maven-hpi-plugin:1.119:validate (default-validate) @ junit ---
[INFO]
[INFO] --- maven-enforcer-plugin:1.3.1:display-info (display-info) @ junit ---
[INFO] Maven Version: 3.3.9
[INFO] JDK Version: 1.8.0_92 normalized as: 1.8.0-92
[INFO] OS Info: Arch: x86_64 Family: mac Name: mac os x Version: 10.12.3
[INFO]
{ ... }
[INFO] ------------------------------------------------------------------------
[INFO] BUILD SUCCESS
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 03:25 min
[INFO] Finished at: 2017-02-06T22:43:41-08:00
[INFO] Final Memory: 84M/1265M
[INFO] ------------------------------------------------------------------------
----


== Conclusion
This new Declarative syntax is a significant step forward for Jenkins Pipeline.
It trades some added some verbosity and constraints for much greater clarity and maintainability.
In the coming weeks, I'll be adding new post every few days demonstrating various
features of the Declarative syntax and recent Jenkins Pipeline.


=== Links

* link
* link
